spring:
  profiles:
    include: secret
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gather?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password:
  
  data: #네이버 api 호출 제한용
    redis:
      host: localhost   # Redis 서버 주소
      port: 6379
  
  jpa:
    hibernate:
      # update: Entity 클래스를 보고 없는 테이블(customer_feedback)을 자동으로 만들어줌
      ddl-auto: update 
    show-sql: true # 콘솔에서 쿼리 확인
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always # 앱 실행 시 data.sql을 항상 실행하여 더미 데이터 세팅
      schema-locations:
        - optional:classpath*:db/gather-full-init.sql
        - optional:classpath*:gather-full-init.sql
        - optional:classpath*:schema.sql
      data-locations:
        - classpath:db/channel-performance-data.sql
        - classpath:db/upload-guide-data.sql
      continue-on-error: true

  thymeleaf:
    cache: false
    servlet:
      produce-partial-output-while-processing: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
